// Mocks generated by Mockito 5.4.6 from annotations
// in calinout/test/features/nutrient_logs/unit/food_operations_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:calinout/core/utils/result.dart' as _i4;
import 'package:calinout/features/nutrient_logs/domain/entities/food.dart'
    as _i5;
import 'package:calinout/features/nutrient_logs/domain/repositories/food_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FoodRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFoodRepository extends _i1.Mock implements _i2.FoodRepository {
  MockFoodRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.Food>> create(_i5.Food? food) =>
      (super.noSuchMethod(
            Invocation.method(#create, [food]),
            returnValue: _i3.Future<_i4.Result<_i5.Food>>.value(
              _i6.dummyValue<_i4.Result<_i5.Food>>(
                this,
                Invocation.method(#create, [food]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Food>>);

  @override
  _i3.Future<_i4.Result<(List<_i5.Food>, bool)>> getAllWithSearch(
    String? searchQuery,
    int? page,
    int? pageSize,
    bool? isTemplate,
    bool? withMealId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllWithSearch, [
              searchQuery,
              page,
              pageSize,
              isTemplate,
              withMealId,
            ]),
            returnValue: _i3.Future<_i4.Result<(List<_i5.Food>, bool)>>.value(
              _i6.dummyValue<_i4.Result<(List<_i5.Food>, bool)>>(
                this,
                Invocation.method(#getAllWithSearch, [
                  searchQuery,
                  page,
                  pageSize,
                  isTemplate,
                  withMealId,
                ]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<(List<_i5.Food>, bool)>>);

  @override
  _i3.Future<_i4.Result<bool>> delete(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i3.Future<_i4.Result<bool>>.value(
              _i6.dummyValue<_i4.Result<bool>>(
                this,
                Invocation.method(#delete, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<bool>>);

  @override
  _i3.Future<_i4.Result<bool>> update(int? id, _i5.Food? food) =>
      (super.noSuchMethod(
            Invocation.method(#update, [id, food]),
            returnValue: _i3.Future<_i4.Result<bool>>.value(
              _i6.dummyValue<_i4.Result<bool>>(
                this,
                Invocation.method(#update, [id, food]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<bool>>);

  @override
  _i3.Future<_i4.Result<(List<_i5.Food>, bool)>> getAll(
    int? page,
    int? pageSize,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [page, pageSize]),
            returnValue: _i3.Future<_i4.Result<(List<_i5.Food>, bool)>>.value(
              _i6.dummyValue<_i4.Result<(List<_i5.Food>, bool)>>(
                this,
                Invocation.method(#getAll, [page, pageSize]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<(List<_i5.Food>, bool)>>);

  @override
  _i3.Future<List<_i5.Food>> getCachedOnly() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedOnly, []),
            returnValue: _i3.Future<List<_i5.Food>>.value(<_i5.Food>[]),
          )
          as _i3.Future<List<_i5.Food>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Food>>> getByDateRange(
    DateTime? start,
    DateTime? end,
    bool? isTemplate,
    bool? showFoodInsideMeal,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getByDateRange, [
              start,
              end,
              isTemplate,
              showFoodInsideMeal,
            ]),
            returnValue: _i3.Future<_i4.Result<List<_i5.Food>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Food>>>(
                this,
                Invocation.method(#getByDateRange, [
                  start,
                  end,
                  isTemplate,
                  showFoodInsideMeal,
                ]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Food>>>);

  @override
  _i3.Future<void> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  bool isCacheStale() =>
      (super.noSuchMethod(
            Invocation.method(#isCacheStale, []),
            returnValue: false,
          )
          as bool);
}
